### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by nojb** [ocaml/ocaml-lsp#1098]
It would be nice to make a new release at the same time as Dune 3.8 to enable using OCaml-LSP with Watch mode on Windows (see #1080).

**Comment by sidkshatriya** [comment]
It would also be great if the next (or subsequent) release of ocaml-lsp used merlin as library rather than a custom vendored version. See https://github.com/ocaml/ocaml-lsp/pull/1070

Merlin is always acquiring fixes and new features and I don't know how often ocaml-lsp is getting then from upstream merlin. It would be simplest if merlin was just an ocaml-lsp library dependency...

**Comment by nojb** [comment]
Friendly ping; Dune 3.8 and Merlin 4.9 have just been released; is there a chance of an OCaml-LSP release to go with them?

**Comment by nojb** [comment]
Thanks!
