### ISSUE TITLE
Not all modules seem to be recognized

### ISSUE THREAD

**Issue by Lupus** [ocaml/ocaml-lsp#129]
I'm trying out ocaml-lsp with https://github.com/ocamllabs/vscode-ocaml-platform, and I can't get completion for modules defined in the same file, hovering also does not work, but when trying completion for `Base.`, it works well and shows me everything. Hovering over `Random` also gives the signature. Is there some additional configuration required? dune 2.2.0, OCaml 4.06.1, .merlin files are in place.

**Comment by Lupus** [comment]
Hm, there's also weird "invalidCharacter.orComment.orString" error shown at the start of the file. Not sure if that's related.

**Comment by Lupus** [comment]
Seems to be related to the "invalidCharacter.orComment.orString" error, nearby file works just fine. Any guidance on what to look for? It's a reason source file that compiles just fine.

**Comment by giltho** [comment]
So this is not really an ocaml-lsp error. The `invalidCharacter.orComment.orString` comes from merlin. But it is not really their fault either.
The issue comes from the Reason tooling (I don't know which part exactly). Basically, unlike OCaml, if there's a single syntax error in the whole file, no analysis can be done on the entire file. There is no resilience to syntax errors in the reason tooling. (I've recently started to play with reason syntax)

Anyway, I'm going to close this issue. Sorry I answered so late, since it was a syntax error I'm guessing this has been fixed for a very long time.

If any Reason user comes across this issue in the future, here's a trick I found : whenever Reason doesn't pinpoint exactly where a syntax error happens, copy-paste the whole file in https://reasonml.github.io/en/try, where the messages are much clearer somehow
