### ISSUE TITLE
String with "-" rendered incorrectly

### ISSUE THREAD

**Issue by Athishpranav2003** [ocaml/ocaml-lsp#1359]
Lsp seems to wrongly parse strings with "-" in them.
![image](https://github.com/user-attachments/assets/719574f9-33bf-47f5-a3d1-3f3a0e807c28)
Environment: OCaml Platform Extension:v1.20.0 (VSCode)
OS: Fedora 40

**Comment by voodoos** [comment]
What exactly do you mean by "wrongly parse" ? I am not able to reproduce you screenshot on my side:
<img width="462" alt="image" src="https://github.com/user-attachments/assets/8d0ff979-03fb-48d3-b55b-befe3fd727f7">

**Comment by Athishpranav2003** [comment]
@voodoos so basically the "in" keyword was also considered as a string in my case(in the screenshot.

**Comment by voodoos** [comment]
Ah I see. I'am still unable to reproduce. I also tried to toggle semantic highlighting on and off.
What version of ocaml-lsp-server are you using ?

**Comment by Athishpranav2003** [comment]
My lsp version is 1.19.0
@voodoos 
```
let _ =  (`Msg " (p−1).(q−1)= 1") in
```

Check this string?
specially this problem is arising with 2 `-` are present
![image](https://github.com/user-attachments/assets/ef4a977a-f706-4065-bfb1-6bd732eac3e9)

**Comment by voodoos** [comment]
Ah right, the issue is different then: the dashes you are using are not the standard ASCII dashes `-`. It explain why vscode highlights them with boxes. This mean they are not actually one character wide and the syntax highlighter gets confused. If you add a few spaces before the `in` key word it does work...

It's not ideal, but that's not a server issue. The simplest workaround is to use actual ASCII dashes.

https://github.com/user-attachments/assets/782f318b-36cf-46e1-99c9-7c379dc5fc1a

**Comment by Athishpranav2003** [comment]
Oh ok
Thanks @voodoos I will close this issue
