### ISSUE TITLE
Logging messages are too noisy

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/ocaml-lsp#145]
I see quite a bit of debug messages that look like:

```
[ocaml-lsp-server] debug: TEXT
open Import

(* Terminology:
   - PackageManager: represents supported package managers
     with Global as the fallback
   - projectRoot is different from PackageManager root (Eg. Opam
     (Path.ofString "/foo/bar")). Project root
     is the directory where manifest file (opam/esy.json/package.json)
     was found. PackageManager root is the directory that contains the
     manifest file responsible for setting up the toolchain - the two
     are same for Esy and Opam project but different for
     bucklescript. Bucklescript projects have this manifest file
     abstracted away from the user (atleast at the moment)
   - Manifest: abstracts functions handling manifest files
     of the supported package managers *)

module PackageManager = struct
  module Kind = struct
    type t =
      | Opam
```

This is far too noisy.

**Comment by giltho** [comment]
In the future, I believe that logging should be done through the  `logTrace` notification, which is in the process of being added to the spec.

The reason is, verbosity (off | message | verbose) is given in the initParams, and the vscode node server implementation uses a non-specificed notification to log. This way, the verbosity is controlled and this kind of noisiness only happens if desired.

In this case for example, the text would only appear in verbose mode.
