### ISSUE TITLE
Type definitions inside ReasonReact components

### ISSUE THREAD

**Issue by dylanirlbeck** [ocaml/ocaml-lsp#152]
Hi! Thanks for creating `ocaml-lsp`. So far it's been a great alternative to Reason language server, and I'm loving it.

I had a question about support for writing JSX in Reason using the `[@react.component]` annotation. It seems that `ocaml-lsp` does not function properly when you're inside the `make` function of a React component. For example, for the code

```reason
module TestComponent = {
  [@react.component]
  let make = (~label, ~value) => {
    let showReset = Belt.Option.isSome(value);
    let value = value->Belt.Option.mapWithDefault("", string_of_int);
    <div>
      ...
    </div>;
  };
};
```

I'm unable to see the proper type of the `value` or `showReset` variables. I instead get this output:

```
{. "label": string, "value": option(int)} => React.element
```

for the type definition, which isn't correct. Is there a way that I can adjust `ocaml-lsp` to work inside ReasonReact components? 

Thank you in advance! I'd be happy to provide more information if necessary.

**Comment by giltho** [comment]
So I'm not 100% sure here, but this might be due to the reason stack.
Bucklescript works with these annotations like [@react.component], and then does modifications on the AST. My guess is that the location origin gets wrongly reassigned. Hence, any variable inside the component gets mapped to entire component node, which actually has the type
```ocaml
{. "label": string, "value": option(int)} => React.element
```
unfortunately this is not something we can do anything about I believe. My guess is that this should be fixed in bucklescript directly.

However, I'm not gonna close this issue just yet, I'll wait for a Reason expert to confirm

**Comment by rickyvetter** [comment]
Yeah this is an issue with the PPX. Tracked in https://github.com/reasonml/reason-react/issues/429

**Comment by giltho** [comment]
Cool, closing the issue then :)
