### ISSUE TITLE
Cancelation Support

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/ocaml-lsp#223]
Whenever vscode is no longer interested in the response of some request, it will send a cancellation notification for that request.

Currently, we just drop these notifications. Since the bottleneck for serving requests is the single merlin thread, the server would be more responsive if we made the effort to cancel the requests.

**Comment by ulugbekna** [comment]
I have the following implementation in mind:

We need to keep track of tasks that are created and added to the merlin worker queue to be able to cancel them. As we cancel those tasks based on the request ID, which is provided in the cancel notification, we need to be able to map a request ID to a task. Since `Document.dispatch` creates tasks that are added to the merlin worker queue, I think it is best if we keep this "track" in `Document` module. 

I think we could create a hashtable `task_keeper` in `Document` that would store `(request_id, task)` pairs. 

- `Document.with_pipeline` would create a task and store `(request_id, task)` in `task_keeper`;
- When the task is completed or cancelled, the task would be removed from `task_keeper`.

Possible downsides to such implementation: 

- We will need to pass request IDs to Ocaml_lsp_server and `Document`, which seems a little like a leak of abstraction
- Mutable state in `Document`

**Comment by rgrinberg** [comment]
Perhaps before we talk about cancellation in the LSP layer, I think we should design something that will work with our jsonrpc implementation first. Once we have a reasonable API, maybe we'll be able to use it to implement LSP specific cancellation on top.

A good start might be to add a function like this:

```ocaml
val try_cancel : (_, _) Context.t -> Id.t -> [`Cancelled | `Failed] Fiber.t
```
Which will attempt to cancel a request that hasn't been served yet.

To make this work with merlin, we'll need a way to keep a request in a "pending" state until merlin resources are available. This seems a little simpler to me. What do you think?

**Comment by ulugbekna** [comment]
Let me then think about this more :)

> until merlin resources are available

i.e., until the merlin worker queue is empty and waiting for tasks?
