### ISSUE TITLE
error message Unix.Unix_error(12, "sleep", "") on WSL1

### ISSUE THREAD

**Issue by arbipher** [ocaml/ocaml-lsp#240]
I found an error message in vscode _OutPut_ from _OCaml Language Server_.

```
Thread 2 killed on uncaught exception Unix.Unix_error(12, "sleep", "")
Raised by primitive operation at Lsp__Scheduler.wake_loop.loop in file "lsp/src/scheduler.ml", line 235, characters 28-59
Called from Thread.create.(fun) in file "thread.ml", line 39, characters 8-14
```

I am new to ocaml-lsp so I cannot decide whether this error is fatal or not.

**Comment by rgrinberg** [comment]
@mnxn have you seen anything like this before? I don't have much experience with WSL1, so I have no idea why `Unix.sleep` might fail.

**Comment by mnxn** [comment]
I haven't personally encountered that error since I don't use WSL 1. WSL 1 doesn't use a real linux kernel like WSL 2, which means it can have bugs like this one.

It seems that this is related to an unpatched glibc on Ubuntu 20: 
https://discourse.ubuntu.com/t/ubuntu-20-04-and-wsl-1/15291 
https://askubuntu.com/questions/1230252/sleep-doesnt-work-on-ubuntu-20-04-wsl

I don't think there's much we can do from our side.

**Comment by rgrinberg** [comment]
Thanks. Indeed, there's not much we can do. @arbipher please re-open if you encounter issues with WSL2 or cygwin.
