### ISSUE TITLE
Lsp_fiber not installed and external users of the `lsp` package

### ISSUE THREAD

**Issue by Gbury** [ocaml/ocaml-lsp#311]
From what I can tell the 1.2 release introduced quite a few breaking changes in the API for the `lsp` package, among them a split of some code into separate sub-libraries, such as `lsp_fiber`. However, as far as I can tell on my installation, `lsp_fiber` is not installed as a library, which leads me to ask the following question:

With the current distribution, what is the suggested way for users who want to build an lsp server ?

Whereas before `lsp` library (together with `lsp.stdun`, and `lsp.fiber`, which is a bit confusing to not mistake with `lsp_fiber`..), allowed one to instantiate and build a binary acting as lsp server, it looks like some of the code required to do so is now in `lsp_fiber` which is not installed. Are users expected to copy the code of `lsp_fiber`, re-implement it, or another solution ?

**Comment by rgrinberg** [comment]
Yes, the fiber implementation is currently hidden because it's not at a stable state at the moment. It's main reason for existing is my dislike for Lwt's error handling and the need to keep dependencies minimal for the lsp server. I don't imagine you have the same problems.

Are you ok with using Lwt? If so, then perhaps @c-cube can contribute his implementation to this repository.

**Comment by Gbury** [comment]
Lwt is fine, i'll see what I can do for my project with @c-cube , ^^

**Comment by rgrinberg** [comment]
Please re-open if @c-cube doesn't help.
