### ISSUE TITLE
Upgrade to LSP 3.16 

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/ocaml-lsp#364]
[LSP 3.16](https://microsoft.github.io/language-server-protocol/specifications/specification-current) has arrived. Creating an issue to track the move to the new version.

**Comment by giltho** [comment]
Hi !

A good thing might be to change in a tiny way the logging works.
Right now, [ocaml-lsp sends logs through `logMessage` requests](https://github.com/ocaml/ocaml-lsp/blob/dccb997604568d377be03d129d76c9b8f7c1a839/ocaml-lsp-server/src/ocaml_lsp_server.ml#L162). For its systematic logging, it should be done through [`$/logTrace`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#logTrace) of which level can be modified at by the Trace value given at initialization, or that can be modified through `$/setTrace`.

To be more precise :
- logging that happens all the time should be done by logTrace
- logging that happens once in a while (for example, there was an error during handling of notification) should be done with logMessage.

The features has always existed in VSCode but was not documented as part of the protocol. The PR to add it to the protocol was written because it was wanted for ocaml-lsp (https://github.com/ocaml/ocaml-lsp/issues/145#issuecomment-610600469, https://github.com/ocaml/ocaml-lsp/pull/120#issuecomment-596493774, https://github.com/microsoft/language-server-protocol/issues/943).

Obviously, this is not a priority **at all** :)
