### ISSUE TITLE
seems to be compiled with OCaml

### ISSUE THREAD

**Issue by rbjorklin** [ocaml/ocaml-lsp#451]
I just encountered a message like the following:
```
/home/rbjorklin/.opam/411/lib//ocaml/stdlib.cmi
seems to be compiled with OCaml 4.11.
But this instance of Merlin handles OCaml 4.12.
```

Which I was able to resolve by removing `.merlin` in my workspace. Could the error message be improved to hint towards the solution?

**Comment by voodoos** [comment]
Merlin gives priority to `.merlin` files if there is one, and asks Dune if there is none. It is not obvious how to give a better error message because it might be the choice of the user to have a custom `.merlin`.

However, since Dune `2.8.3`, old `.merlin` files that were generated by versions of Dune `< 2.8.0` should be automatically deleted on the first build.

**Comment by rbjorklin** [comment]
Alright if there isn't anything to be done here I'll just close the issue. At least the next time someone hits this there will be one hit on google :sweat_smile:
