### ISSUE TITLE
It gives a wrong type for optional arguments

### ISSUE THREAD

**Issue by Ailrun** [ocaml/ocaml-lsp#65]
For demonstration, with the following code,
```
let x ?(a=1) b: bool = a + b > 0
let y = x ~a:3 5
```
ocaml-lsp gives me `bool`, i.e., the result type of `x` when I put a cursor on `~a:` part, but I think it is bit misleading and it would be better to give `int`, i.e., the type of the `a` argument.

**Comment by Ailrun** [comment]
Maybe this also applies to labelled arguments, but I didn't check it.

**Comment by giltho** [comment]
@Ailrun it comes from merlin. According to what I understand, it's because merlin types expressions, and in the case of `let y = x ~a:3 5`, `~a` is not an expression, it's simply a label, therefore it gives you the expression type of the smallest enclosing expression which is `x ~a:3 5` (and actually, that is what is highlighted when your cursor is over ~a : 
![image](https://user-images.githubusercontent.com/8451179/72445416-95c5f280-37a9-11ea-8a1e-305f45c40739.png)

not that if you write this :
```ocaml
let x ?(a=1) b: bool = a + b > 0
let a = 3
let y = x ~a 5
```
and hover the `~a`, you get the correct type (`int`) because here, `a` is an expression that is actually the variable `a`.
You could submit an issue asking to type labels as the expression they annotate, but that should be done in [merlin](https://github.com/ocaml/merlin) I think.
I'll let a more experienced collaborator of ocaml-lsp confirm what I'm saying and close the issue if it is correct

**Comment by Ailrun** [comment]
@giltho Thanks, I checked this with `merlin` and confirmed that it did the same with `merlin`, so I made ocaml/merlin#1084.

I will close this issue.
